type Api = {
  system: {
    login: (data: Record<string, unknown>) => Promise<DecryptBody<{ access_token: string,refresh_token:string }>>,
    logout: () => Promise<DecryptBody>,
    getLogList: (params: Record<string, unknown>) => Promise<DecryptBody<Log.GetLoggerListApi>>,
    uploadFile: (file: FormData) => Promise<DecryptBody<{ url: string }>>,
  },
  user: {
    getUserinfo: () => Promise<DecryptBody<SystemUser.UserInfo>>,
    createUser: (data: Record<string, unknown>) => Promise<DecryptBody>,
    updateUser:(data: Record<string, unknown>) => Promise<DecryptBody>,
    delUser: (data: any) => Promise<DecryptBody>,
    changeUserStatus: (data: Record<string, unknown>) => Promise<DecryptBody>,
    getUserList: (params: Record<string, unknown>) => Promise<DecryptBody<SystemUser.GetUserListApi>>,
  },
  role: {
    getRoleList: (params: Record<string, unknown>) => Promise<DecryptBody<Role.GetRoleListApi>>,
    getRoleInfo: (id: number) => Promise<DecryptBody<Role.RoleInfo>>,
    createRole: (data: Record<string, unknown>) => Promise<DecryptBody>,
    updateRole: (data: Record<string, unknown>) => Promise<DecryptBody>,
    delRole: (data:any) => Promise<DecryptBody>,
    getRoleOption: () => Promise<DecryptBody<GlobalOptions<number>[]>>,
  },
  menu: {
    getMenuList: (params: Record<string, unknown>) => Promise<DecryptBody<Menu.GetMenuListApi>>,
    getMenuOptions: () => Promise<DecryptBody<TreeOptions[]>>,
    createMenu: (data: Record<string, unknown>) => Promise<DecryptBody>,
    updateMenu: (data: Record<string, unknown>) => Promise<DecryptBody>,
    delMenu: (data: any) => Promise<DecryptBody>,
    getMenuInfo: (id: number) => Promise<DecryptBody<Menu.MenuRow>>,
    changeMenuStatus: (data: Record<string, unknown>) => Promise<DecryptBody>,
  },
  permissions: {
    getPermissionsList: (params: Record<string, unknown>) => Promise<DecryptBody<Permissions.GetPermissionsListApi>>,
    createPermissions: (data: Record<string, unknown>) => Promise<DecryptBody>,
    updatePermissions: (data: Record<string, unknown>) => Promise<DecryptBody>,
    delPermissions: (data: any) => Promise<DecryptBody>,
    getPermissionsInfo: (id: number) => Promise<DecryptBody<Permissions.PermissionsInfo>>,
    getPermissionsOptions: () => Promise<DecryptBody<TreeOptions[]>>,
  },
  config: {
    getConfigList: (params: Record<string, unknown>) => Promise<DecryptBody<SystemConfig.ConfigRow[]>>,
    getConfigById: (id: number) => Promise<DecryptBody<SystemConfig.ConfigRow>>,
    createConfig: (data: Record<string, unknown>) => Promise<DecryptBody>,
    updateConfig: (data: Record<string, unknown>) => Promise<DecryptBody>,
    updateConfigEnable: (data: Record<string, unknown>) => Promise<DecryptBody>,
    delConfig: (data: any) => Promise<DecryptBody>,
  },
  department: {
    getDepartmentOptions: () => Promise<DecryptBody<GlobalOptions<number>[]>>,
    getDepartmentList: (params: Record<string, unknown>) => Promise<DecryptBody<Department.GetDepartmentListApi>>,
    getDepartmentInfo: (id: number) => Promise<DecryptBody<Department.DepartmentRow>>,
    createDepartment: (data: Record<string, unknown>) => Promise<DecryptBody>,
    updateDepartment: (data: Record<string, unknown>) => Promise<DecryptBody>,
    delDepartment: (data: any) => Promise<DecryptBody>,
    changeDepartmentStatus: (data: Record<string, unknown>) => Promise<DecryptBody>,
  },
  dict: {
    getDictList: (params: Record<string, unknown>) => Promise<DecryptBody<Dict.GetDictListStructApi>>,
    createDict: (data: Record<string, unknown>) => Promise<DecryptBody>,
    updateDict: (data: Record<string, unknown>) => Promise<DecryptBody>,
    delDict: (data: any) => Promise<DecryptBody>,
    getDictInfo: (id: number) => Promise<DecryptBody<Dict.DictRow>>,
    getDictType: (type: string) => Promise<DecryptBody<GlobalOptions[]>>,
    getDictTypeList: (params: Record<string, unknown>) => Promise<DecryptBody<Dict.GetDictTypeListStructApi>>,
    delDictType: (data: any) => Promise<DecryptBody>,
    createDictType: (data: Record<string, unknown>) => Promise<DecryptBody>,
    updateDictType: (data: Record<string, unknown>) => Promise<DecryptBody>,
    changeDictStatus: (data: Record<string, unknown>) => Promise<DecryptBody>,
    getDefaultDiceOptions: () => Promise<DecryptBody<DefaultOptions[]>>,
  }
}
